development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: Research-Library_development
  pool: 5
  host: localhost
  username: kvadrats
  password: secret

test:
  adapter: postgresql
  encoding: SQL_ASCII
  database: Research-Library_test
  host: localhost
  pool: 5
  username: kvadrats
  password: secret
