development:
  adapter: postgresql
  encoding: unicode
  database: Research-Library_development
  pool: 5
  username: emilskantans
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: Research-Library_test
  pool: 5
  username: emilskantans
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Research-Library_production
  pool: 5
  username: emilskantans
  password: 